apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

namespace: hipster-shop-prod

commonLabels:
  environment: prod

images:
  - name: server
    newName: gcr.io/google-samples/microservices-demo/cartservice:v0.1.3
  
bases:
  - ../../cartservice