controller:
  replicaCount: 3
  config:
    log-format-escape-json: "true"
    log-format-upstream: '{"remote_addr": "$remote_addr", 
      "remote_user": "$remote_user", 
      "time_local": "$time_iso8601", 
      "request": "$request", 
      "status": "$status", 
      "body_bytes_sent": "$body_bytes_sent", 
      "http_referer": "$http_referer", 
      "http_user_agent": "$http_user_agent", 
      "request_length": "$request_length", 
      "request_time": "$request_time"}'

  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - nginx-ingress
            topologyKey: kubernetes.io/hostname

  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool
